config/routes.rb
Ggwc::Application.routes.draw do
  get "/join" => "home#membership", :as => "membership"
  get "/about" => "home#about", :as => "about"
  get "/calendar" => "home#calendar", :as => "calendar"
  root :to => 'home#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end


  def membership
  end
end

app/controllers/index_controller.rb
class HomeController < ApplicationController
  def index
  end


  def membership
  end


  def about
  end


  def calendar
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row-fluid">
<div class="span4">
    <div class="widget floating-element">
        <h4>JOIN</h4>
        <p>
            Golden Gate Wrestling Club is open to anyone with an interest in
            freestyle wrestling or Greco-Roman wrestling. This includes men and
            women at all skill levels. Height, weight, gender, race, age,
            disability, and intelligence can be mixed in any proportion to
            produce good wrestlers &mdash; and good coaches!
        </p>
        <a href="<%= membership_url -%>" class="btn btn-primary btn-block">JOIN</a>
    </div>
</div>

<div class="span4">
    <div class="widget floating-element about">
        <img src="assets/wrestling-watercolor.jpg" />
        <p>
            Golden Gate Wrestling Club is a non-profit, volunteer-run club
            devoted to the promotion of amateur wrestling in the San Francisco
            Bay Area. Run with the cooperation and support of the San Francisco
            Park and Recreation Department, GGWC offers coaching, training and
            competition opportunities for local freestyle, Greco-Roman and
            folkstyle wrestlers.
        </p>
    </div>
</div>

<div class="span4">
    <div class="widget floating-element">
        <h4>PRACTICE</h4>
        <p>
            Practices are held at <a href="http://goo.gl/maps/U7v1Y" target="_blank">Eureka Valley Rec Center, 18th and Collingwood</a>.
        </p>
        <ul class="schedule">
            <li>Tuesday/Friday: 7-9pm</li>
            <li>Saturday: noon-2pm</li>
        </ul>
    </div>
</div>

<% content_for :styles do -%>
  <%= stylesheet_link_tag "home", :media => "all" %>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Golden Gate Wrestling Club</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= content_for :styles -%>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="page-wrap">
      <div class="container">
          <div class="row">
              <div class="span12">
                  <div id="page-frame">
                      <div id="page-header" class="floating-element">
                          <ul id="page-tabs">
                              <li class="active">
                                  <a href="<%= root_url -%>">HOME</a>
                              </li>
                              <li>
                                  <a href="<%= membership_url -%>">MEMBERSHIP</a>
                              </li>
                              <li>
                                  <a href="<%= calendar_url -%>">CALENDAR</a>
                              </li>
<!--
                              <li>
                                  <a href="#">GALLERY</a>
                              </li>
-->
                              <li class="last">
                                  <a href="<%= about_url -%>">ABOUT</a>
                              </li>
                          </ul>
                      </div>

                      <div id="page-body">
                          <%= yield %>
                          <div class="clearfix"></div>
                      </div>

                      <div id="page-footer"></div>

                      <div class="clearfix"></div>
                  </div>
              </div>
          </div>
      </div>
  </div>

  <script src="http:////ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
  <%= javascript_include_tag "application" %>
  <%= content_for :scripts -%>
</body>
</html>